version: 2
updates:
  # Maintain dependencies for GitHub Actions
  # src: https://github.com/marketplace/actions/build-and-push-docker-images#keep-up-to-date-with-github-dependabot
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Rust/Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "quarterly"
    open-pull-requests-limit: 10
